version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/sample-niginx/
hooks:
  AfterInstall:
   - location: setup.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: start.nginx
     timeout: 300
     runas: root
